テキスト教材検索機能の実装
yanbaru-expert/team_project_41 pull request #43
Opened 2021-02-18 06:12 UTC by hayato-1221

## issue 番号（必須）

close #42 
​
## 実装内容
​
- テキスト教材の検索機能の実装

## 参考資料
​

- [railsで検索フォームを作ろう！！](https://qiita.com/yusuko/items/cff4e46aeafbc3beecf2)
​
## チェックリスト
​
【補足】プルリクを出した後，クリックでチェックを入れて下さい
​
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
​
## スクリーンショット（必要があれば）
​
​
## 備考（必要があれば）

2021-02-21 21:54 UTC, T-Tsujii requested changes

2021-02-21 21:54 UTC, T-Tsujii commented on app/assets/stylesheets/application.scss
> + width: 350px;
form タグ全体にスタイルを付けるのは避けましょう。影響範囲が大きすぎます。
クラスを付け，そのクラスに対してのみ定義すべきです。

また，widthを決めてしまうと例えば横幅の短いiPhone SEで表示が崩れます。max-widthを使うべきですね。

2021-02-21 21:54 UTC, T-Tsujii commented on app/controllers/texts_controller.rb
> +    @texts = Text.search(params[:search])
こちら使用していないですね。

```suggestion
```

2021-02-21 21:54 UTC, T-Tsujii commented on app/models/text.rb
> +  end
```suggestion
```

2021-02-21 21:54 UTC, T-Tsujii commented on app/views/layouts/application.html.erb
> +    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
Rails 6 の場合は jsは 原則 Yarn 経由で入れてください。

こちらが参考になるでしょう。
https://www.yanbaru-code.com/texts/271

2021-02-22 01:50 UTC, T-Tsujii approved these changes
LGTMです！

2021-02-23 03:03 UTC, Izushi reviewed
LGTMです！

2021-02-23 03:14 UTC, merged