Common parts utilization
yanbaru-expert/team_project_41 pull request #45
Opened 2021-02-24 03:02 UTC by Izushi

## issue 番号（必須）

close #44 
​
## 実装内容
​
- 一覧ページの共通化
  - 各教材の一覧ページへのリンクをtext_pathとしgenreを指定することで、表示する教材を制限する。
  - controllerでは指定されたgenreの教材だけ取得するようにする。

-管理者画面のスタイルが他のビューに反映されないように設定
​
## 参考資料

- 管理者画面
  - https://www.yanbaru-code.com/texts/220
​
## チェックリスト
​
【補足】プルリクを出した後，クリックでチェックを入れて下さい
​
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
​
## スクリーンショット（必要があれば）
​
​
## 備考（必要があれば）

2021-02-24 05:08 UTC, T-Tsujii requested changes

2021-02-24 05:08 UTC, T-Tsujii commented on app/views/layouts/_header.html.erb
> +  <%= link_to "やんばるCODE", texts_path(genre: ["Basic","Git","Ruby","Ruby on Rails"]), class: "navbar-brand" %>
配列を渡すことはできません。何も埋め込まないのも1つの方法です。

```suggestion
  <%= link_to "やんばるCODE", texts_path, class: "navbar-brand" %>
```

2021-02-24 05:08 UTC, T-Tsujii commented on app/controllers/texts_controller.rb
> +    @texts = Text.where(genre: params[:genre])
ここで `params[:genre]` が nil になっている場合は条件分岐するようにしましょう。

2021-02-24 07:10 UTC, T-Tsujii approved these changes
LGTMです！

2021-02-25 06:26 UTC, T-Tsujii approved these changes
LGTMです！

2021-02-25 06:43 UTC, hayato-1221 approved these changes
LGTMです！

2021-02-25 06:46 UTC, merged