フッターナビバーの実装　
yanbaru-expert/team_project_41 pull request #47
Opened 2021-02-25 17:10 UTC by yuukinakamura0925

close #46 
​
## フッターナビバーの実装
​
- application.html.erbにてフッターの追加
  - _footer.html.erbの作成と実装
​
## 参考資料

- Boostrap
  - [やんばるエキスパート教材](Bootstrap教材（その1））
​
## チェックリスト
​
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
​

2021-02-25 22:03 UTC, T-Tsujii requested changes

2021-02-25 22:03 UTC, T-Tsujii commented on app/views/layouts/_footer.html.erb
> +  <%= link_to "Youtube", "https://www.youtube.com/channel/UCwrDvYey9uKGBeh_l5IF-ag", class: "navbar-brand" %>
別タブで開くようにしましょう。

2021-02-25 22:03 UTC, T-Tsujii commented on app/views/movies/index.html.erb
> +/
```suggestion
```

2021-02-26 03:29 UTC, T-Tsujii approved these changes
LGTMです！

2021-02-26 12:57 UTC, hayato-1221 approved these changes
LGTMです！

2021-02-26 13:04 UTC, Izushi approved these changes
LGTMです！

2021-02-26 13:16 UTC, merged